//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureApiComponent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProduct
    {
        public int CustomerProductID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SoldByID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
